- name: play1
  hosts: all
  gather_facts: false
  tasks:
   - name: install many servies
     apt:
       name: "{{ item }}"
       state: latest
     loop:
       - curl
       - nginx
       - foo
   
      
     

# - name: play2
#   hosts: all
#   gather_facts: false
#   tasks:
#     -  name : install curl
#        apt:
#         name : curl
#         state : present