- name: play1
  hosts: all
  gather_facts: false
  tasks:
    - name : who am i
      command : whoami
    - name : ping
      ping :
    - name : install nginx
      apt:
        name: nginx
        state: present
      
     

# - name: play2
#   hosts: all
#   gather_facts: false
#   tasks:
#     -  name : install curl
#        apt:
#         name : curl
#         state : present