- name: play1
  hosts: all
  gather_facts: false
  vars:
    package_name: nginx
    package_state: latest
  tasks:
    - name : install nginx
      apt:
        name : "{{package_name}}"
        state : "{{package_state}}"
      
     

# - name: play2
#   hosts: all
#   gather_facts: false
#   tasks:
#     -  name : install curl
#        apt:
#         name : curl
#         state : present